namespace LeetCode.Test;

public class _0168_ExcelSheetColumnTitle_Test
{
    [Theory]
    [InlineData(1, "A")]
    [InlineData(2, "B")]
    [InlineData(3, "C")]
    [InlineData(4, "D")]
    [InlineData(5, "E")]
    [InlineData(6, "F")]
    [InlineData(7, "G")]
    [InlineData(8, "H")]
    [InlineData(9, "I")]
    [InlineData(10, "J")]
    [InlineData(11, "K")]
    [InlineData(12, "L")]
    [InlineData(13, "M")]
    [InlineData(14, "N")]
    [InlineData(15, "O")]
    [InlineData(16, "P")]
    [InlineData(17, "Q")]
    [InlineData(18, "R")]
    [InlineData(19, "S")]
    [InlineData(20, "T")]
    [InlineData(21, "U")]
    [InlineData(22, "V")]
    [InlineData(23, "W")]
    [InlineData(24, "X")]
    [InlineData(25, "Y")]
    [InlineData(26, "Z")]
    [InlineData(27, "AA")]
    [InlineData(28, "AB")]
    [InlineData(29, "AC")]
    [InlineData(30, "AD")]
    [InlineData(31, "AE")]
    [InlineData(32, "AF")]
    [InlineData(33, "AG")]
    [InlineData(34, "AH")]
    [InlineData(35, "AI")]
    [InlineData(36, "AJ")]
    [InlineData(37, "AK")]
    [InlineData(38, "AL")]
    [InlineData(39, "AM")]
    [InlineData(40, "AN")]
    [InlineData(41, "AO")]
    [InlineData(42, "AP")]
    [InlineData(43, "AQ")]
    [InlineData(44, "AR")]
    [InlineData(45, "AS")]
    [InlineData(46, "AT")]
    [InlineData(47, "AU")]
    [InlineData(48, "AV")]
    [InlineData(49, "AW")]
    [InlineData(50, "AX")]
    [InlineData(51, "AY")]
    [InlineData(52, "AZ")]
    [InlineData(53, "BA")]
    [InlineData(701, "ZY")]
    [InlineData(913, "AIC")]
    public void ConvertToTitle(int columnNumber, string expected)
    {
        var sut = new _0168_ExcelSheetColumnTitle();
        var actual = sut.ConvertToTitle(columnNumber);
        Assert.Equal(expected, actual);
    }
}
